name: Test main

# Cntrols when the action will run
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    env:
      COML_DEBUG: 1

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry"

      - name: Fix windows bash
        if: ${{ matrix.os == 'windows-latest' }}
        run: rm.exe "C:/WINDOWS/system32/bash.EXE"

      - name: Set path to bash for example runner
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo "SHELL_EXECUTABLE=C:\Program Files\Git\bin\bash.exe" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          python -m poetry install

      - name: Lint
        run: python -m poetry run bash scripts/lint.sh

      - name: Test
        run: python -m poetry run bash scripts/test-coverage.sh

      - name: Upload coverage
        if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v2
